### PR TITLE
REF: Use AttributeSignal and ArrayAttributeSignal from ophyd.signal

### PR DESCRIPTION
**Pull request by licode**

### CODE REVIEW

**Comment by licode** [comment]
@danielballan  @mrakitin

**Comment by mrakitin** [comment]
It would be good to have tests automatically running on Travis. There are already a few: https://github.com/NSLS-II/hklpy/tree/master/tests.

**Comment by danielballan** [comment]
I could also see just making this a subpackage in ophyd sooner than later. I could be wrong, but I don't think there is any good reason to maintain it as a separate package.

**Comment by licode** [comment]
Agree. But now, we can use AttributeSignal and ArrayAttribteSignal from ophyd directly, no need to keep another version here.

**Comment by mrakitin** [comment]
Here are some thoughts:
1. That example in this repo has some imports from `ophyd.hkl.diffract`: https://github.com/NSLS-II/hklpy/blob/4023ec0eabeb026d4dee9c71cc13b976864cfa51/examples/hkl_test.py#L5-L9 (discovered with running pytest for the whole repo). I think there was a previous attempt to integrate it.
2. https://github.com/NSLS-II/ophyd/pull/209 seems to be that attempt, right @klauer?

**Comment by mrakitin** [comment]
**Update:** I tested the fix with https://github.com/NSLS-II-CSX/xf23id1_profiles_simulated, and it loaded fine. Not sure what are the best commands to run to fully execute the hklpy features (and underlying `hkl` and `gobject-introspection`).

I agree that we should use `AttributeSignal` and `ArrayAttributeSignal` from ophyd.

**Comment by klauer** [comment]
It started out as part of ophyd. My opinion is that until you can solidify the implementation, it should remain a separate package.

Additionally, hkl library packaging was always a nightmare. Is it better now?

**Comment by mrakitin** [comment]
Thanks for the update, @klauer! Yes, eventually we figured out the proper way to build it 🤞. See https://github.com/NSLS-II/lightsource2-recipes/pull/472 . Now it needs just 4 libraries to be built: `gobject-introspection` -> `pygobject` -> `hkl` -> `hklpy`.

Also, I pushed an update 51c62f1 to use the classes from ophyd rather than having duplicate copies.

**Comment by mrakitin** [comment]
Have you ever evaluated https://github.com/DiamondLightSource/diffcalc? @stuartcampbell mentioned it today.

**Comment by klauer** [comment]
Arman did evaluate diffcalc before the hkl stuff got pushed onto me. If I recall correctly, he said it was too tied in with gda, and I don't think he ever got it working.

If you can get it going, it may be a more easily maintainable path forward...

**Comment by licode** [comment]
No test is needed, as we do import from ophyd directly. LGTM.

**Comment by danielballan** [comment]
This had a merge commit in it and should not have been self-merged. I think it is probably not worth force-pushing, but this is something to watch for.

**Pull request merged**
